---

name: Test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/karras/archlinux-package-build:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Refresh and update packages
        run: |
          pacman -Syu --noconfirm

      - name: Assign ownership to builder user (hacky)
        run: |
          chown -R builder ./

      - name: Build packages
        run: |
          for PACKAGE in */PKGBUILD; do
            cd ${PACKAGE%%/*}
            sudo -u builder \
              makepkg --noconfirm --syncdeps --install
            cd ..
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./*/*.tar.zst
